### PR TITLE
Demo link need to be updated

### PR DESCRIPTION
**Pull request by Pana**
Please update the demo link

### CODE REVIEW

**Comment by yqrashawn** [comment]
The link works fine on my side.
https://conflux-portal-docs.conflux-chain.org/docs/portal/Examples/e2e_test_demo/

Do you mean change it to a more formal one?

**Comment by Pana** [comment]
The [web page](https://developer.conflux-chain.org/docs/conflux-portal/docs/en/portal/API_Reference/signing_data_with_portal) links to https://developer.conflux-chain.org/docs/conflux-portal/e2e_test_demo/

**Comment by yqrashawn** [comment]
Got it. 

It jumps to different place from developer.conflux-chain.org and conflux-portal-docs.conflux-chain.org.

**Comment by Pana** [comment]
It's seems that we should remove the old api documentation of portal

**Comment by yqrashawn** [comment]
fixed with #25

**Pull request closed without merging**
